# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lovecount',
            field=models.IntegerField(default=0),
        ),
    ]
