# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
